Completed React learning Path
tinkerhub/maker-station pull request #11
Opened 2023-03-24 16:34 UTC by Sandra-Rosa

2023-03-25 19:04 UTC, sreehari2003 commented on Web Dev/FrontEnd/Libraries & Frameworks/React JS .md
> +- [React JS Documentation](https://legacy.reactjs.org/docs/getting-started.html)
React recently changed thier docs the new docs url is 
   this    https://react.dev/

2023-03-25 19:06 UTC, sreehari2003 commented on Web Dev/FrontEnd/Libraries & Frameworks/React JS .md
> +- Create React App
it would be better to add vite or next js here ,  new react docs dont recomend create-react-app anymore ! (not manditory though)

2023-03-25 19:08 UTC, sreehari2003 commented on Web Dev/FrontEnd/Libraries & Frameworks/React JS .md
> +    - This project will require advanced-level knowledge of React, backend integration, WebSockets, and server-side rendering.
it would be very good if you can provide a live Github repo link to at least a few of the projects listed here, (again not mandatory)

2023-03-26 04:07 UTC, advaith-unnikrishnan requested changes
@Sandra-Rosa  kindly go through the suggestions made by @sreehari2003 and change the learning path accordingly. If you need any help let me know.

2023-03-27 16:56 UTC, sreehari2003 approved these changes

2023-03-28 11:27 UTC, advaith-unnikrishnan approved these changes

2023-03-28 11:28 UTC, merged